export const SET_CHAT_ROOM_ID = 'SET_CHAT_ROOM_ID';
export const UPDATE_USERS_ONLINE = 'UPDATE_USERS_ONLINE';
export const SAVE_MESSAGE = 'SAVE_MESSAGE';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const RESET_NEW_MESSAGE = 'RESET_NEW_MESSAGE';